[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.7.4", features = ["json", "original-uri"] }
tokio = { version = "1.36.0", features = ["full"] }

anyhow = "1.0.80"

serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"

base64 = "0.22.0"
