[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.20", features = ["json", "original-uri", "headers"] }
tokio = { version = "1.34.0", features = ["full"] }

anyhow = "1.0.75"

serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"

base64 = "0.21.5"
