[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.19", features = ["json", "original-uri", "headers"] }
tokio = { version = "1.29.1", features = ["full"] }

anyhow = "1.0.72"

serde = { version = "1.0.180", features = ["derive"] }
serde_json = "1.0.104"

base64 = "0.21.2"
