name: ci
on:
  pull_request:
    branches:
      - main

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: latest
          run_install: true
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: server Lint
        run: cargo clippy --all
      - name: server test
        run: cargo test --all
      - name: Build WebAssembly package
        run: wasm-pack build --release -t web ./packages/novel/data/
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test
